---
- name: "Automate Dockerfile Build using Ansible"
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop python-proj
      ignore_errors: yes

    - name: remove stopped container 
      command: docker rm python-proj
      ignore_errors: yes

    - name: remove old image 
      command: docker rmi abdullahmarey/python-app
      ignore_errors: yes

    - name: build new image
      command: docker build -t abdullahmarey/python-app . 

    - name: push new image to dockerhub
      command: docker push abdullahmarey/python-app

    - name: running new container 
      command: docker run -d --name python-proj -p 8000:8000 abdullahmarey/python-app



